name: release

on:
  push:
    paths:
      - 'Surfing.json'

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      isAlpha: false

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Get version number
        id: version
        run: |
          version=$(grep 'version=' module.prop | awk -F '=' '{print $2}')
          echo "TAG_NAME=${version}" >> $GITHUB_ENV
          echo "Version extracted: ${version}"

      - name: Run build.sh
        run: sh build.sh

      - name: Determine Tag Name
        id: tag
        run: echo "TAG_NAME=${{ env.TAG_NAME }}" >> $GITHUB_ENV

      - name: Upload Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.TAG_NAME }}
          files: Surfing_v*.zip
          generate_release_notes: true
          body: ${{ github.event.inputs.release_notes }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
